fix: Update .github/workflows/run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -548,7 +548,7 @@ jobs:
                 ((attempt++))
                 continue
               fi
-              echo ""Non-retriable error: ${status}"" >&2
+              echo "Non-retriable error: ${status}" >&2
               return 22
             done
             echo "Exceeded retries. Last status: ${status}" >&2
